language: python

python:
  - "3.6.7"

install:
  - pip install -r requirements.txt

before_script:
  - export BASE_URL="$BASE_URL"
  - export API_KEY="$API_KEY"
  - export API_USERNAME=$API_USERNAME

script:
  - flake8 pysendyit
  - nosetests --with-coverage --cover-erase --cover-package=pysendyit

after_success:
  - coveralls
